/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Agent;

import static Agent.TokoGUI.lblPesan;
import java.awt.Color;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Adri
 */
public class GrosirGUI extends javax.swing.JFrame {

    /**
     * Creates new form GrosirGUI
     */
    public GrosirGUI() {
        initComponents();
//        DbOperate dO = new DbOperate();
//        try {
//            dO.ngeTestRead();
//        } catch (Exception ex) {
//            Logger.getLogger(GrosirGUI.class.getName()).log(Level.SEVERE, null, ex);
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGrosirStatus = new javax.swing.JLabel();
        cbGrosirBarang = new javax.swing.JComboBox();
        txtGrosirJml = new javax.swing.JTextField();
        btnGrosirKirim = new javax.swing.JButton();
        btnDismiss = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Grosir");

        lblGrosirStatus.setText("Tidak Ada Permintaan");

        cbGrosirBarang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sabun", "Pasta Gigi", "Shampo" }));

        btnGrosirKirim.setText("Kirim");
        btnGrosirKirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGrosirKirimActionPerformed(evt);
            }
        });

        btnDismiss.setText("Dismiss");
        btnDismiss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDismissActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblGrosirStatus, javax.swing.GroupLayout.DEFAULT_SIZE, 488, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDismiss)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(cbGrosirBarang, 0, 141, Short.MAX_VALUE)
                                .addComponent(txtGrosirJml)
                                .addComponent(btnGrosirKirim, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(lblGrosirStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDismiss)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(cbGrosirBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtGrosirJml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnGrosirKirim)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnDismissActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDismissActionPerformed
        // TODO add your handling code here:
        lblGrosirStatus.setForeground(Color.BLACK);
        lblGrosirStatus.setText("Tidak Ada Permintaan");
    }//GEN-LAST:event_btnDismissActionPerformed

    private void btnGrosirKirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGrosirKirimActionPerformed
        // TODO add your handling code here:
        if (Toko.status_permintaan == true) {
            if (txtGrosirJml.getText().isEmpty() == false) {
                Grosir.status_permintaan = true;
                int jml = Integer.parseInt(txtGrosirJml.getText());
                String nama_barang = cbGrosirBarang.getSelectedItem().toString();
                if (txtGrosirJml.getText().isEmpty() == false) {
                    if (nama_barang.equalsIgnoreCase("sabun")) {
                        int jml_sabun = Integer.parseInt(TokoGUI.lblJmlSabun.getText());
                        jml_sabun += jml;
                        TokoGUI.lblJmlSabun.setText(String.valueOf(jml_sabun));
                    } else if (nama_barang.equalsIgnoreCase("pasta gigi")) {
                        int jml_pasta_gigi = Integer.parseInt(TokoGUI.lblJmlPastaGigi.getText());
                        jml_pasta_gigi += jml;
                        TokoGUI.lblJmlPastaGigi.setText(String.valueOf(jml_pasta_gigi));
                    } else {
                        int jml_shampo = Integer.parseInt(TokoGUI.lblJmlShampo.getText());
                        jml_shampo += jml;
                        TokoGUI.lblJmlShampo.setText(String.valueOf(jml_shampo));
                    }
                    txtGrosirJml.setText("");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Please Enter A Value!", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            JOptionPane.showMessageDialog(null, "There are no requests!", "Error", JOptionPane.ERROR_MESSAGE);

        }
        Toko.status_permintaan = false;
        lblPesan.setForeground(Color.black);
        lblGrosirStatus.setText("Tidak Ada Permintaan");
    }//GEN-LAST:event_btnGrosirKirimActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GrosirGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GrosirGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GrosirGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GrosirGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GrosirGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDismiss;
    private javax.swing.JButton btnGrosirKirim;
    private javax.swing.JComboBox cbGrosirBarang;
    public static javax.swing.JLabel lblGrosirStatus;
    private javax.swing.JTextField txtGrosirJml;
    // End of variables declaration//GEN-END:variables
}
