/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package Agent;

import javax.swing.table.DefaultTableModel;
import Agent.Toko;
import java.awt.Color;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import model.Barang;
import utility.DbOperate;

/**
 *
 * @author Adri
 */
public class TokoGUI extends javax.swing.JFrame {

    /**
     * Creates new form TokoGUI
     */
    
    public static int sabun;
    public static int pasta_gigi;
    public static int shampo;
    
    public TokoGUI() {
        sabun = 0;
        pasta_gigi = 0;
        shampo = 0;
        
        initComponents();
        
        DbOperate dO = new DbOperate();
        try {
            List<Barang> lb = dO.getBarang();
            Iterator iLb = lb.iterator();
            while(iLb.hasNext()){
                Barang barang = (Barang) iLb.next();
                if(barang.getNama_barang().equals("shampo")){
                    lblJmlShampo.setText(String.valueOf(barang.getStok_barang()));
                } else if(barang.getNama_barang().equals("sabun")){
                    lblJmlSabun.setText(String.valueOf(barang.getStok_barang()));
                } else {
                    lblJmlPastaGigi.setText(String.valueOf(barang.getStok_barang()));
                }
            }
        } catch (Exception ex) {
            Logger.getLogger(TokoGUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        cbTokoBarang = new javax.swing.JComboBox();
        txtTokoJml = new javax.swing.JTextField();
        btnTokoMeminta = new javax.swing.JButton();
        lblPesan = new javax.swing.JLabel();
        btnDismiss = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblJmlSabun = new javax.swing.JLabel();
        lblJmlPastaGigi = new javax.swing.JLabel();
        lblJmlShampo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Toko");

        cbTokoBarang.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Sabun", "Pasta Gigi", "Shampo" }));

        btnTokoMeminta.setText("Meminta");
        btnTokoMeminta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTokoMemintaActionPerformed(evt);
            }
        });

        lblPesan.setText("Tidak Ada Pesan");

        btnDismiss.setText("Dismiss");
        btnDismiss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDismissActionPerformed(evt);
            }
        });

        jLabel1.setText("Sabun");

        jLabel2.setText("Pasta Gigi");

        jLabel3.setText("Shampo");

        lblJmlSabun.setText("0");

        lblJmlPastaGigi.setText("0");

        lblJmlShampo.setText("0");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblPesan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtTokoJml)
                                .addComponent(cbTokoBarang, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnTokoMeminta, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnDismiss)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblJmlSabun)
                                    .addComponent(lblJmlShampo)
                                    .addComponent(lblJmlPastaGigi))))
                        .addGap(0, 339, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblJmlSabun))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblJmlPastaGigi))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblJmlShampo)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(cbTokoBarang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtTokoJml, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTokoMeminta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblPesan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnDismiss)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTokoMemintaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTokoMemintaActionPerformed
        // TODO add your handling code here:
        Toko.status_permintaan = true;
        Toko.nama_barang = cbTokoBarang.getSelectedItem().toString();
        Toko.jml = Integer.parseInt(txtTokoJml.getText());
        txtTokoJml.setText("");
        lblPesan.setText("Tidak Ada Pesan");
    }//GEN-LAST:event_btnTokoMemintaActionPerformed

    private void btnDismissActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDismissActionPerformed
        // TODO add your handling code here:
        lblPesan.setForeground(Color.BLACK);
        lblPesan.setText("Tidak Ada Pesan");
    }//GEN-LAST:event_btnDismissActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TokoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TokoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TokoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TokoGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TokoGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDismiss;
    private javax.swing.JButton btnTokoMeminta;
    private javax.swing.JComboBox cbTokoBarang;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    public static javax.swing.JLabel lblJmlPastaGigi;
    public static javax.swing.JLabel lblJmlSabun;
    public static javax.swing.JLabel lblJmlShampo;
    public static javax.swing.JLabel lblPesan;
    private javax.swing.JTextField txtTokoJml;
    // End of variables declaration//GEN-END:variables
}
